apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 80
    protocol: TCP
  selector:
    app: brain-tasks-app
